name: structa-test-suite

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
            python: "3.7"
            experimental: false
          - os: ubuntu-20.04
            python: "3.8"
            experimental: false
          - os: ubuntu-20.04
            python: "3.9"
            experimental: false
          - os: ubuntu-22.04
            python: "3.10"
            experimental: false
          - os: ubuntu-22.04
            python: "3.11"
            experimental: false

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - name: Install Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Checkout structa
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          make develop

      - name: Run tests
        run: |
          make test
